repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        language_version: python3.8
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ["--safe"]
        language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        language_version: python3.8

  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 6.0.0
  #   hooks:
  #     - id: pydocstyle
  #       language_version: python3.8
  #       exclude: ".*(test|alembic|scripts).*"
